packages:
  - 'packages/*'
  - 'adaptors/*'
  - 'projects/*'
  - 'examples/*'
  - 'documentions'
  - '../cvo-framework/packages/*'
  - '../cvo-framework/plugins/*'
  - '../cvo-framework/adaptors/*'
  - '../Programs/projects/gm'
  - '../Programs/projects/common'
